apiVersion: v1
kind: Secret
metadata:
  name: catalog-db
  namespace: retail-app
type: Opaque
stringData:
  RETAIL_CATALOG_PERSISTENCE_USER: "<catalog_db_username>"
  RETAIL_CATALOG_PERSISTENCE_PASSWORD: "<catalog_db_password>"
---
apiVersion: v1
kind: Secret
metadata:
  name: orders-db
  namespace: retail-app
type: Opaque
stringData:
  RETAIL_ORDERS_PERSISTENCE_USERNAME: "<orders_db_username>"
  RETAIL_ORDERS_PERSISTENCE_PASSWORD: "<orders_db_password>"
---
apiVersion: v1
kind: Secret
metadata:
  name: orders-rabbitmq
  namespace: retail-app
type: Opaque
stringData:
  RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME: "<rabbitmq_username>"
  RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD: "<rabbitmq_password>"
